In [ ]:
# Penalized Regression Techniques

In [ ]:
# L1- Lasso Regression
# L2- Ridge Regression
# Enet- Elastic Net 

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.cross_validation import cross_val_score
from sklearn.linear_model import LinearRegression

/Applications/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
from sklearn import datasets, linear_model
from sklearn import cross_validation as cv
from scipy import linalg

In [3]:
bhdata = datasets.load_boston()

featuredata = bhdata.data

colnames = bhdata.feature_names #variable names

data = pd.DataFrame(featuredata,columns=colnames) # predictors of MEDV
data['target'] = bhdata.target #median value of housing prices

In [4]:
data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [5]:
data.shape

(506, 14)

In [7]:
13*50

650

In [8]:
data.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.593761   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.596783   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.647423   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT      target  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [9]:
#split the dataset into training and testig 
data_train, data_test = cv.train_test_split(data,test_size=0.30,random_state=34)

In [10]:
data_train.shape,data_test.shape

((354, 14), (152, 14))

In [11]:
corr = data.corr()
corr

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
CRIM     1.000000 -0.199458  0.404471 -0.055295  0.417521 -0.219940  0.350784   
ZN      -0.199458  1.000000 -0.533828 -0.042697 -0.516604  0.311991 -0.569537   
INDUS    0.404471 -0.533828  1.000000  0.062938  0.763651 -0.391676  0.644779   
CHAS    -0.055295 -0.042697  0.062938  1.000000  0.091203  0.091251  0.086518   
NOX      0.417521 -0.516604  0.763651  0.091203  1.000000 -0.302188  0.731470   
RM      -0.219940  0.311991 -0.391676  0.091251 -0.302188  1.000000 -0.240265   
AGE      0.350784 -0.569537  0.644779  0.086518  0.731470 -0.240265  1.000000   
DIS     -0.377904  0.664408 -0.708027 -0.099176 -0.769230  0.205246 -0.747881   
RAD      0.622029 -0.311948  0.595129 -0.007368  0.611441 -0.209847  0.456022   
TAX      0.579564 -0.314563  0.720760 -0.035587  0.668023 -0.292048  0.506456   
PTRATIO  0.288250 -0.391679  0.383248 -0.121515  0.188933 -0.355501  0.261515   
B       -0.377365  0.175520 -0.356977  0.048788 -0.380051  0.128069 -0.273534   
LSTAT    0.452220 -0.412995  0.603800 -0.053929  0.590879 -0.613808  0.602339   
target  -0.385832  0.360445 -0.483725  0.175260 -0.427321  0.695360 -0.376955   

              DIS       RAD       TAX   PTRATIO         B     LSTAT    target  
CRIM    -0.377904  0.622029  0.579564  0.288250 -0.377365  0.452220 -0.385832  
ZN       0.664408 -0.311948 -0.314563 -0.391679  0.175520 -0.412995  0.360445  
INDUS   -0.708027  0.595129  0.720760  0.383248 -0.356977  0.603800 -0.483725  
CHAS    -0.099176 -0.007368 -0.035587 -0.121515  0.048788 -0.053929  0.175260  
NOX     -0.769230  0.611441  0.668023  0.188933 -0.380051  0.590879 -0.427321  
RM       0.205246 -0.209847 -0.292048 -0.355501  0.128069 -0.613808  0.695360  
AGE     -0.747881  0.456022  0.506456  0.261515 -0.273534  0.602339 -0.376955  
DIS      1.000000 -0.494588 -0.534432 -0.232471  0.291512 -0.496996  0.249929  
RAD     -0.494588  1.000000  0.910228  0.464741 -0.444413  0.488676 -0.381626  
TAX     -0.534432  0.910228  1.000000  0.460853 -0.441808  0.543993 -0.468536  
PTRATIO -0.232471  0.464741  0.460853  1.000000 -0.177383  0.374044 -0.507787  
B        0.291512 -0.444413 -0.441808 -0.177383  1.000000 -0.366087  0.333461  
LSTAT   -0.496996  0.488676  0.543993  0.374044 -0.366087  1.000000 -0.737663  
target   0.249929 -0.381626 -0.468536 -0.507787  0.333461 -0.737663  1.000000

In [12]:
XTrain = data_train.iloc[:,0:(data.shape[1]-1)].as_matrix()
YTrain = data_train['target']

/Applications/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [13]:
XTest = data_test.iloc[:,0:(data.shape[1]-1)].as_matrix()
YTest = data_test['target']

/Applications/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [14]:
XTrain.shape, XTest.shape

((354, 13), (152, 13))

In [15]:
#multiple linear regression model
reg = linear_model.LinearRegression(normalize=True)
reg

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=True)

In [16]:
reg.fit(XTrain,YTrain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=True)

In [22]:
print('Coefficients: \n', np.round(reg.coef_,1))

Coefficients: 
 [ -0.1   0.1   0.1   2.5 -19.5   3.1   0.   -1.3   0.3  -0.   -1.    0.
  -0.6]


In [18]:
reg.score(XTrain,YTrain)

0.7304342787291502

In [19]:
reg.score(XTest,YTest)

0.7454024922510339

In [26]:
from scipy import stats

In [23]:
#adjusted R square
def AdjustedRSquare(model,X,Y):
    YHat = model.predict(X)
    n,k = X.shape
    sse = np.sum(np.square(YHat-Y),axis=0)
    sst = np.sum(np.square(Y-np.mean(Y)),axis=0)
    R2 = 1- sse/sst
    adjR2 = R2-(1-R2)*(float(k)/(n-k-1))
    return adjR2, R2

In [24]:
def ReturnPValue(model,X,Y):
    YHat = model.predict(X)
    n,k = X.shape
    sse = np.sum(np.square(YHat-Y),axis=0)
    x = np.hstack((np.ones((n,1)),np.matrix(X)))
    df = float(n-k-1)
    sampleVar = sse/df
    sampleVarianceX = x.T*x
    covarianceMatrix = linalg.sqrtm(sampleVar*sampleVarianceX.I)
    se = covarianceMatrix.diagonal()[1:]
    betasTstat = np.zeros(len(se))
    for i in range(len(se)):
        betasTstat[i] = model.coef_[i]/se[i]
    betasPvalue = 1- stats.t.cdf(abs(betasTstat),df)
    return betasPvalue

In [29]:
np.round(ReturnPValue(reg,XTrain,YTrain),2)

array([0.02, 0.  , 0.14, 0.01, 0.  , 0.  , 0.01, 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  ])

In [30]:
reg.adjR2, reg.R2 = AdjustedRSquare(reg,XTrain,YTrain)
print (reg.adjR2, reg.R2)

0.7201273540923236 0.7304342787291502


In [31]:
def ErrorMetric(model,X,Y):
    Yhat = model.predict(X)
    MAPE = np.mean(abs(Y-Yhat)/Y)*100
    MSSE = np.mean(np.square(Y-Yhat))
    return MAPE, MSSE

In [32]:
ErrorMetric(reg,XTrain,YTrain)

(16.456212903959756, 22.789606639490117)

In [33]:
ErrorMetric(reg,XTest,YTest)

(17.68072414079735, 21.325629855583912)

In [34]:
alpha = 0.05
erroR = 1

In [35]:
reg.BetasPValue = ReturnPValue(reg,XTrain,YTrain)

In [36]:
MAPE, prevMSSE = ErrorMetric(reg,XTest,YTest)
MAPE, prevMSSE

(17.68072414079735, 21.325629855583912)

In [37]:
while (erroR > 0.001):
    ind = np.where(reg.BetasPValue>alpha)[0]
    if(len(ind)==0):
        ind = np.argmax(reg.BetasPValue)
        
    XTrain = np.delete(XTrain,ind,axis=1)
    XTest = np.delete(XTest,ind,axis=1)
    
    reg.fit(XTrain,YTrain)
    
    reg.BetasPValue = ReturnPValue(reg,XTrain, YTrain)
    MAPE, MSSE = ErrorMetric(reg,XTest,YTest)

    erroR = prevMSSE - MSSE
print (erroR, MSSE)

-0.6560767242382894 21.9817065798222


In [41]:
np.round(reg.coef_,1)

array([  0.1,   2.7, -17.2,   3.1,   0. ,  -1.3,   0.3,  -0. ,  -1. ,
         0. ,  -0.6])

In [38]:
data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [42]:
data.RAD.value_counts()

24.0    132
5.0     115
4.0     110
3.0      38
6.0      26
8.0      24
2.0      24
1.0      20
7.0      17
Name: RAD, dtype: int64

In [43]:
RAD_Dummies = pd.get_dummies(data.RAD,prefix='RAD',drop_first=True)

In [44]:
RAD_Dummies.head(10)

RAD_2.0  RAD_3.0  RAD_4.0  RAD_5.0  RAD_6.0  RAD_7.0  RAD_8.0  RAD_24.0
0        0        0        0        0        0        0        0         0
1        1        0        0        0        0        0        0         0
2        1        0        0        0        0        0        0         0
3        0        1        0        0        0        0        0         0
4        0        1        0        0        0        0        0         0
5        0        1        0        0        0        0        0         0
6        0        0        0        1        0        0        0         0
7        0        0        0        1        0        0        0         0
8        0        0        0        1        0        0        0         0
9        0        0        0        1        0        0        0         0

In [45]:
modeldata = pd.concat([data,RAD_Dummies],axis=1)

In [46]:
modeldata.head(2)

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   

     ...     LSTAT  target  RAD_2.0  RAD_3.0  RAD_4.0  RAD_5.0  RAD_6.0  \
0    ...      4.98    24.0        0        0        0        0        0   
1    ...      9.14    21.6        1        0        0        0        0   

   RAD_7.0  RAD_8.0  RAD_24.0  
0        0        0         0  
1        0        0         0  

[2 rows x 22 columns]

In [47]:
df_train, df_test = cv.train_test_split(modeldata,test_size=0.30,random_state=1234)

In [48]:
df_train.shape, df_test.shape

((354, 22), (152, 22))

In [49]:
XTrain = df_train.iloc[:,list(range(7)) + list(range(9,13)) + list(range(15,df_train.shape[1]))].as_matrix()
YTrain = df_train['target']

/Applications/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [50]:
XTest = df_test.iloc[:,list(range(7)) + list(range(9,13)) + list(range(15,df_test.shape[1]))].as_matrix()
YTest = df_test['target']

/Applications/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [51]:
XTrain.shape,YTrain.shape

((354, 18), (354,))

In [52]:
reg

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=True)

In [58]:
regr = linear_model.LinearRegression()

In [59]:
regr.fit(XTrain,YTrain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [60]:
regr.score(XTrain,YTrain)

0.6955572461418931

In [61]:
regr.MAPE, regr.MSSE = ErrorMetric(regr,XTest,YTest)
regr.MAPE, regr.MSSE

(18.16032205622921, 23.781195443785492)

In [62]:
regr.adjR2, regr.R2 = AdjustedRSquare(regr,XTrain,YTrain)
print (regr.adjR2, regr.R2)

0.6791991280241441 0.6955572461418931


In [70]:
# Polynomial features
# We can try Polynomial Rergession 
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import StandardScaler

In [64]:
# two kinds of polynomial features:
# base features =13
# transforming the individual features (degree 2= 13)
# creating interaction features (13C2 = 78)

In [63]:
78+26

104

In [66]:
from sklearn.preprocessing import StandardScaler

In [67]:
scaler = StandardScaler()

In [68]:
X = scaler.fit_transform(bhdata['data'])

In [69]:
pd.DataFrame(X).head()

0         1         2         3         4         5         6   \
0 -0.417713  0.284830 -1.287909 -0.272599 -0.144217  0.413672 -0.120013   
1 -0.415269 -0.487722 -0.593381 -0.272599 -0.740262  0.194274  0.367166   
2 -0.415272 -0.487722 -0.593381 -0.272599 -0.740262  1.282714 -0.265812   
3 -0.414680 -0.487722 -1.306878 -0.272599 -0.835284  1.016303 -0.809889   
4 -0.410409 -0.487722 -1.306878 -0.272599 -0.835284  1.228577 -0.511180   

         7         8         9         10        11        12  
0  0.140214 -0.982843 -0.666608 -1.459000  0.441052 -1.075562  
1  0.557160 -0.867883 -0.987329 -0.303094  0.441052 -0.492439  
2  0.557160 -0.867883 -0.987329 -0.303094  0.396427 -1.208727  
3  1.077737 -0.752922 -1.106115  0.113032  0.416163 -1.361517  
4  1.077737 -0.752922 -1.106115  0.113032  0.441052 -1.026501

In [71]:
poly = PolynomialFeatures(2)

In [72]:
poly

PolynomialFeatures(degree=2, include_bias=True, interaction_only=False)

In [73]:
Xpoly = poly.fit_transform(X)

In [74]:
Xpoly.shape

(506, 105)

In [75]:
print (len(Xpoly))

506


In [76]:
x = Xpoly
Y = bhdata['target']

In [77]:
# interaction features
featurenames = ['intercept'] + list(bhdata['feature_names'])

polyfeaturenames = [];

for i,x in enumerate(featurenames):
    for y in featurenames[i:]:
        if (x == 'intercept'):
            polyfeaturenames.append(y)
        elif (x==y):
            polyfeaturenames.append((y+'_Square'))
        else:
            polyfeaturenames.append((x+'_'+y))

print(featurenames)


['intercept', 'CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT']


In [78]:
print (polyfeaturenames)

['intercept', 'CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'CRIM_Square', 'CRIM_ZN', 'CRIM_INDUS', 'CRIM_CHAS', 'CRIM_NOX', 'CRIM_RM', 'CRIM_AGE', 'CRIM_DIS', 'CRIM_RAD', 'CRIM_TAX', 'CRIM_PTRATIO', 'CRIM_B', 'CRIM_LSTAT', 'ZN_Square', 'ZN_INDUS', 'ZN_CHAS', 'ZN_NOX', 'ZN_RM', 'ZN_AGE', 'ZN_DIS', 'ZN_RAD', 'ZN_TAX', 'ZN_PTRATIO', 'ZN_B', 'ZN_LSTAT', 'INDUS_Square', 'INDUS_CHAS', 'INDUS_NOX', 'INDUS_RM', 'INDUS_AGE', 'INDUS_DIS', 'INDUS_RAD', 'INDUS_TAX', 'INDUS_PTRATIO', 'INDUS_B', 'INDUS_LSTAT', 'CHAS_Square', 'CHAS_NOX', 'CHAS_RM', 'CHAS_AGE', 'CHAS_DIS', 'CHAS_RAD', 'CHAS_TAX', 'CHAS_PTRATIO', 'CHAS_B', 'CHAS_LSTAT', 'NOX_Square', 'NOX_RM', 'NOX_AGE', 'NOX_DIS', 'NOX_RAD', 'NOX_TAX', 'NOX_PTRATIO', 'NOX_B', 'NOX_LSTAT', 'RM_Square', 'RM_AGE', 'RM_DIS', 'RM_RAD', 'RM_TAX', 'RM_PTRATIO', 'RM_B', 'RM_LSTAT', 'AGE_Square', 'AGE_DIS', 'AGE_RAD', 'AGE_TAX', 'AGE_PTRATIO', 'AGE_B', 'AGE_LSTAT', 'DIS_Square', 'DIS_RAD', 'DIS_TAX', 'DIS_PTR

In [79]:
Xpoly.shape

(506, 105)

In [80]:
regr2 = linear_model.LinearRegression()

regr2

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [81]:
regr2.fit(Xpoly,Y)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [82]:
regr2.score(Xpoly,Y)

0.9291260169776512

In [83]:
regr2.adjR2, regr2.R2 = AdjustedRSquare(regr2,Xpoly,Y)
print (regr2.adjR2, regr2.R2)


0.9105215964342847 0.9291260169776512


In [86]:
np.round(ReturnPValue(regr2,Xpoly,Y),1)

/Applications/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:13: ComplexWarning: Casting complex values to real discards the imaginary part
  del sys.path[0]


array([0.5, 0.1, 0. , 0.2, 0. , 0.1, 0. , 0. , 0. , 0.2, 0.2, 0. , 0.1,
       0. , 0.3, 0.1, 0. , 0. , 0. , 0. , 0.1, 0. , 0.3, 0.2, 0.1, 0. ,
       0. , 0.5, 0.1, 0.1, 0. , 0.3, 0.5, 0. , 0.2, 0. , 0.1, 0.1, 0.1,
       0. , 0.5, 0.3, 0. , 0.1, 0. , 0.3, 0.2, 0.3, 0.1, 0.2, 0. , 0. ,
       0. , 0.4, 0.2, 0.4, 0.4, 0.1, 0.1, 0.1, 0.5, 0.4, 0.1, 0. , 0.1,
       0. , 0. , 0.2, 0. , 0. , 0. , 0.4, 0.3, 0. , 0. , 0.1, 0. , 0.2,
       0.3, 0. , 0. , 0.5, 0. , 0. , 0. , 0. , 0.1, 0. , 0.2, 0. , 0. ,
       0. , 0.1, 0.4, 0. , 0. , 0. , 0.3, 0.2, 0.5, 0.1, 0.3, 0. , 0.1,
       0. ])

In [87]:
print (polyfeaturenames)

['intercept', 'CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'CRIM_Square', 'CRIM_ZN', 'CRIM_INDUS', 'CRIM_CHAS', 'CRIM_NOX', 'CRIM_RM', 'CRIM_AGE', 'CRIM_DIS', 'CRIM_RAD', 'CRIM_TAX', 'CRIM_PTRATIO', 'CRIM_B', 'CRIM_LSTAT', 'ZN_Square', 'ZN_INDUS', 'ZN_CHAS', 'ZN_NOX', 'ZN_RM', 'ZN_AGE', 'ZN_DIS', 'ZN_RAD', 'ZN_TAX', 'ZN_PTRATIO', 'ZN_B', 'ZN_LSTAT', 'INDUS_Square', 'INDUS_CHAS', 'INDUS_NOX', 'INDUS_RM', 'INDUS_AGE', 'INDUS_DIS', 'INDUS_RAD', 'INDUS_TAX', 'INDUS_PTRATIO', 'INDUS_B', 'INDUS_LSTAT', 'CHAS_Square', 'CHAS_NOX', 'CHAS_RM', 'CHAS_AGE', 'CHAS_DIS', 'CHAS_RAD', 'CHAS_TAX', 'CHAS_PTRATIO', 'CHAS_B', 'CHAS_LSTAT', 'NOX_Square', 'NOX_RM', 'NOX_AGE', 'NOX_DIS', 'NOX_RAD', 'NOX_TAX', 'NOX_PTRATIO', 'NOX_B', 'NOX_LSTAT', 'RM_Square', 'RM_AGE', 'RM_DIS', 'RM_RAD', 'RM_TAX', 'RM_PTRATIO', 'RM_B', 'RM_LSTAT', 'AGE_Square', 'AGE_DIS', 'AGE_RAD', 'AGE_TAX', 'AGE_PTRATIO', 'AGE_B', 'AGE_LSTAT', 'DIS_Square', 'DIS_RAD', 'DIS_TAX', 'DIS_PTR

In [88]:
regr2.MAPE, regr2.MSSE = ErrorMetric(regr2,Xpoly,Y)
print (regr2.MAPE, regr2.MSSE)

9.37570483464 5.98238096594


In [84]:
print (regr.coef_)
print (regr2.coef_)

[-6.23532988e-02  2.18815262e-02  9.33831537e-02  2.93246737e+00
 -1.12203719e+01  3.08879122e+00  4.38326907e-02 -1.11281058e-02
 -1.19295071e+00  9.35517059e-03 -6.24797151e-01  3.28814392e+00
  1.77814685e+00  1.52238661e+00  1.03030167e+00  1.85835407e+00
  1.95998592e+00  8.04547118e+00]
[ 1.81611926e-13  1.57665018e+01  1.47611930e+01  9.30060316e+00
  5.51296355e+12 -1.90460738e+00  3.51716363e+00 -2.09468607e+00
 -2.48226340e+00  5.04995728e+00 -9.96044922e+00  1.14816284e+00
  1.41833496e+00 -3.15487671e+00  1.28906250e-01  4.29869690e+01
  2.32109680e+01  5.45343781e+00 -7.90142059e-01  7.95166016e-01
 -8.20800781e-01 -1.71902466e+00  1.58240356e+01 -3.45885925e+01
  7.20971680e+00 -2.49023438e-01  1.27465820e+00 -2.73437500e-01
 -8.47961426e-01 -3.62945557e-01 -2.84338379e+00  2.29736328e-01
  4.01611328e-02 -5.18249512e-01 -1.00244141e+00  2.50384521e+00
 -3.47167969e-01  1.38677979e+00 -7.67517090e-01  1.87072754e+00
  1.28173828e-02  9.75494385e-01  1.42590332e+00  6.7331

In [110]:
# Null: beta estimates are = 0
# Alt : beta estimates are != 0

In [111]:
# to restrict the model overfitting
# regularized regression models

# LASSO - L1
# Ridge - L2

In [88]:
from sklearn.linear_model import Lasso

In [89]:
XTrain, XTest, YTrain, YTest = cv.train_test_split(Xpoly,Y, test_size=0.25,random_state=1234)

In [90]:
XTrain.shape, XTest.shape, YTrain.shape, YTest.shape

((379, 105), (127, 105), (379,), (127,))

In [104]:
lassoMod = Lasso(alpha=0.9)

In [105]:
lassoMod.fit(XTrain,YTrain)

Lasso(alpha=0.9, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [106]:
print (lassoMod.coef_)

[ 0.         -0.          0.         -0.          0.         -0.
  1.60382283 -0.         -0.         -0.         -0.         -0.70429969
  0.         -3.95787901 -0.07571673  0.         -0.          0.
 -0.         -0.         -0.          0.         -0.         -0.
  0.          0.         -0.          0.04929968 -0.          0.
  0.          0.         -0.         -0.         -0.         -0.
 -0.         -0.         -0.          0.          0.         -0.
 -0.         -0.          0.         -0.         -0.          0.
  0.         -0.          0.19527776 -0.         -0.          0.
 -0.          0.          0.          0.          0.         -0.
 -0.         -0.         -0.          0.         -0.         -0.
 -0.          0.         -0.          0.74650573 -0.          0.
 -0.         -0.0340048  -1.01962221  0.         -0.21112427  0.
  0.         -0.         -0.         -0.         -0.         -0.
 -0.          0.          0.          0.         -0.          0.
 -0.         -0. 

In [107]:
lassoMod.coef_[((lassoMod.coef_)!=0)]

array([ 1.60382283, -0.70429969, -3.95787901, -0.07571673,  0.04929968,
        0.19527776,  0.74650573, -0.0340048 , -1.01962221, -0.21112427,
       -0.25906646])

In [114]:
lassoMod = Lasso(alpha=1)
lassoMod.fit(XTrain,YTrain)
print (lassoMod.coef_)

[ 0.         -0.          0.         -0.          0.         -0.
  1.56671904 -0.         -0.         -0.         -0.         -0.65869171
  0.         -3.84587689 -0.07509719  0.         -0.          0.
 -0.         -0.         -0.          0.         -0.         -0.
  0.          0.         -0.          0.06358342 -0.          0.
  0.          0.         -0.         -0.         -0.         -0.
 -0.         -0.         -0.          0.          0.         -0.
 -0.         -0.          0.         -0.         -0.          0.
  0.         -0.          0.19172068 -0.         -0.          0.
 -0.          0.          0.          0.          0.         -0.
 -0.         -0.         -0.          0.         -0.         -0.
 -0.          0.         -0.          0.77646759 -0.          0.
 -0.         -0.         -0.99781114  0.         -0.12441185  0.
  0.         -0.         -0.         -0.          0.         -0.
 -0.          0.          0.          0.         -0.          0.
 -0.         -0. 

In [115]:
lassoMod.coef_[((lassoMod.coef_)!=0)]

array([ 1.56671904, -0.65869171, -3.84587689, -0.07509719,  0.06358342,
        0.19172068,  0.77646759, -0.99781114, -0.12441185, -0.26430648])

In [116]:
names = [polyfeaturenames[i] for i in list(np.where(lassoMod.coef_ != 0.0)[0])]
names

['RM',
 'PTRATIO',
 'LSTAT',
 'CRIM_Square',
 'ZN_Square',
 'CHAS_Square',
 'RM_Square',
 'RM_PTRATIO',
 'RM_LSTAT',
 'B_Square']

In [117]:
lassoMod.MAPE, lassoMod.MSSE = ErrorMetric(lassoMod, XTrain, YTrain)

In [118]:
print (lassoMod.MAPE, lassoMod.MSSE)

15.060888003991582 19.778325325465484


In [119]:
lassoMod.MAPE, lassoMod.MSSE = ErrorMetric(lassoMod, XTest, YTest)

In [120]:
print (lassoMod.MAPE, lassoMod.MSSE)

18.831077871575708 21.268210339425263


In [121]:
from sklearn.linear_model import Ridge


In [122]:
ridgeMod1 = Ridge(alpha=1)
ridgeMod1.fit(XTrain,YTrain)
names = [polyfeaturenames[i] for i in list(np.where(ridgeMod1.coef_ != 0.0)[0])]
print(names)
ridgeMod1.MAPE, ridgeMod1.MSSE = ErrorMetric(ridgeMod1, XTrain, YTrain)
print (ridgeMod1.MAPE, ridgeMod1.MSSE)


['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'CRIM_Square', 'CRIM_ZN', 'CRIM_INDUS', 'CRIM_CHAS', 'CRIM_NOX', 'CRIM_RM', 'CRIM_AGE', 'CRIM_DIS', 'CRIM_RAD', 'CRIM_TAX', 'CRIM_PTRATIO', 'CRIM_B', 'CRIM_LSTAT', 'ZN_Square', 'ZN_INDUS', 'ZN_CHAS', 'ZN_NOX', 'ZN_RM', 'ZN_AGE', 'ZN_DIS', 'ZN_RAD', 'ZN_TAX', 'ZN_PTRATIO', 'ZN_B', 'ZN_LSTAT', 'INDUS_Square', 'INDUS_CHAS', 'INDUS_NOX', 'INDUS_RM', 'INDUS_AGE', 'INDUS_DIS', 'INDUS_RAD', 'INDUS_TAX', 'INDUS_PTRATIO', 'INDUS_B', 'INDUS_LSTAT', 'CHAS_Square', 'CHAS_NOX', 'CHAS_RM', 'CHAS_AGE', 'CHAS_DIS', 'CHAS_RAD', 'CHAS_TAX', 'CHAS_PTRATIO', 'CHAS_B', 'CHAS_LSTAT', 'NOX_Square', 'NOX_RM', 'NOX_AGE', 'NOX_DIS', 'NOX_RAD', 'NOX_TAX', 'NOX_PTRATIO', 'NOX_B', 'NOX_LSTAT', 'RM_Square', 'RM_AGE', 'RM_DIS', 'RM_RAD', 'RM_TAX', 'RM_PTRATIO', 'RM_B', 'RM_LSTAT', 'AGE_Square', 'AGE_DIS', 'AGE_RAD', 'AGE_TAX', 'AGE_PTRATIO', 'AGE_B', 'AGE_LSTAT', 'DIS_Square', 'DIS_RAD', 'DIS_TAX', 'DIS_PTRATIO', 'DIS_B

In [123]:
ridgeMod1 = Ridge(alpha=0)
ridgeMod1.fit(XTrain,YTrain)
names = [polyfeaturenames[i] for i in list(np.where(ridgeMod1.coef_ != 0.0)[0])]
print(names)
ridgeMod1.MAPE, ridgeMod1.MSSE = ErrorMetric(ridgeMod1, XTrain, YTrain)
print (ridgeMod1.MAPE, ridgeMod1.MSSE)


['intercept', 'CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'CRIM_Square', 'CRIM_ZN', 'CRIM_INDUS', 'CRIM_CHAS', 'CRIM_NOX', 'CRIM_RM', 'CRIM_AGE', 'CRIM_DIS', 'CRIM_RAD', 'CRIM_TAX', 'CRIM_PTRATIO', 'CRIM_B', 'CRIM_LSTAT', 'ZN_Square', 'ZN_INDUS', 'ZN_CHAS', 'ZN_NOX', 'ZN_RM', 'ZN_AGE', 'ZN_DIS', 'ZN_RAD', 'ZN_TAX', 'ZN_PTRATIO', 'ZN_B', 'ZN_LSTAT', 'INDUS_Square', 'INDUS_CHAS', 'INDUS_NOX', 'INDUS_RM', 'INDUS_AGE', 'INDUS_DIS', 'INDUS_RAD', 'INDUS_TAX', 'INDUS_PTRATIO', 'INDUS_B', 'INDUS_LSTAT', 'CHAS_Square', 'CHAS_NOX', 'CHAS_RM', 'CHAS_AGE', 'CHAS_DIS', 'CHAS_RAD', 'CHAS_TAX', 'CHAS_PTRATIO', 'CHAS_B', 'CHAS_LSTAT', 'NOX_Square', 'NOX_RM', 'NOX_AGE', 'NOX_DIS', 'NOX_RAD', 'NOX_TAX', 'NOX_PTRATIO', 'NOX_B', 'NOX_LSTAT', 'RM_Square', 'RM_AGE', 'RM_DIS', 'RM_RAD', 'RM_TAX', 'RM_PTRATIO', 'RM_B', 'RM_LSTAT', 'AGE_Square', 'AGE_DIS', 'AGE_RAD', 'AGE_TAX', 'AGE_PTRATIO', 'AGE_B', 'AGE_LSTAT', 'DIS_Square', 'DIS_RAD', 'DIS_TAX', 'DIS_PTR

In [126]:
from sklearn.grid_search import GridSearchCV

In [127]:
XTrain, XTest, YTrain, YTest = cv.train_test_split(Xpoly,Y, test_size=0.25,random_state=1234)

In [128]:
XTrain.shape, XTest.shape, YTrain.shape, YTest.shape

((379, 105), (127, 105), (379,), (127,))

In [129]:
from sklearn.cross_validation import ShuffleSplit

In [130]:
from sklearn.metrics import r2_score

In [131]:
def performance_metric(y_true, y_predict):
    score = r2_score(y_true, y_predict)
    return score

In [132]:
from sklearn.metrics import make_scorer

In [149]:
def fit_model(X,y):
    cv_sets = ShuffleSplit(XTrain.shape[0],n_iter=10,
                           test_size=0.20,
                           random_state=1234)
    ridgeModel = Ridge()
    params = {'alpha':list(range(0,12)),
             'solver' : ('auto', 
                         'svd', 
                         'cholesky', 
                         'lsqr', 
                         'sparse_cg', 
                         'sag', 
                         'saga')}
    scoring_func = make_scorer(performance_metric)
    grid = GridSearchCV(ridgeModel,params,scoring_func,cv=cv_sets)
    grid = grid.fit(X,y)
    return grid.best_estimator_

In [144]:
fit_model(XTrain,YTrain)

Ridge(alpha=3, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='lsqr', tol=0.001)

In [135]:
final_model = fit_model(XTrain,YTrain)

In [136]:
ErrorMetric(final_model, XTrain, YTrain)

(9.139265804201493, 5.8608954980636)

In [137]:
ErrorMetric(final_model, XTest, YTest)

(13.354858213035003, 11.024816351071685)

In [138]:
regr2.adjR2, regr2.R2 = AdjustedRSquare(final_model, XTrain, YTrain)
print (regr2.adjR2, regr2.R2)

0.8964048305630299 0.9251812665177438


In [139]:
regr2.adjR2, regr2.R2 = AdjustedRSquare(final_model, XTest, YTest)
print (regr2.adjR2, regr2.R2)

0.35315659003428523 0.8921927650057142


In [146]:
from sklearn.linear_model import 

In [148]:
enet = ElasticNet()

In [152]:
np.round(final_model.coef_,2)

array([ 0.  , -0.04,  0.15,  0.52,  0.13, -1.25,  3.03, -1.48, -2.64,
        1.32, -1.47, -0.2 ,  0.53, -3.59,  0.1 , -0.01,  0.02,  2.32,
       -0.69,  0.95,  0.19,  0.17, -1.09,  0.29, -0.36, -0.26,  0.63,
       -0.  ,  0.16, -0.02, -0.24,  0.37, -0.29, -0.44, -0.36,  1.65,
       -0.03,  0.28, -0.49,  0.96,  0.55,  1.48,  0.78,  0.28,  0.57,
       -0.03, -0.04, -0.59,  0.51, -0.76,  0.43, -1.28, -1.2 ,  0.45,
        0.81, -0.01,  0.91, -0.55, -0.11, -0.65, -0.41,  0.48, -1.02,
        1.19, -1.38,  0.59, -0.58, -0.11,  1.07,  0.11, -1.55, -0.35,
       -0.91, -1.81, -0.48, -0.21, -1.25,  0.04, -0.33,  2.01, -0.73,
       -0.36, -1.15, -1.59,  1.16, -1.64, -0.85, -0.25, -0.97,  0.84,
       -1.61,  1.01,  0.64,  0.04, -1.34, -0.39,  2.11, -0.36, -1.18,
        0.1 ,  0.03,  0.16, -0.28, -0.7 ,  0.56])